name: geonotes
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter


  flutter_bloc: ^9.1.1
  supabase_flutter: ^2.9.0
  flutter_dotenv: ^5.2.1
  onesignal_flutter: ^5.3.3
  get_it: ^8.0.3
  google_maps_flutter: ^2.12.3
  easy_localization: ^3.0.7
  dart_mappable: ^4.5.0


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
